version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.3.0-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672" # RabbitMQ broker port
      - "15672:15672" # Management UI port
    networks:
      - rabbit-net

  # postgres:
  # image: postgres:17
  # container_name: postgres-container
  # environment:
  #   POSTGRES_DB: CustomerData
  #   POSTGRES_USER: postgres
  #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  # ports:
  #   - "5432:5432"
  # networks:
  #   - rabbit-net

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile # Source of the image to pull from
    container_name: springboot-container
    ports:
      - "8080:8080" # Expose your app to your local machine
    depends_on:
      - rabbitmq # Ensures RabbitMQ starts first
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq # Mentions the service name as host
      - SPRING_RABBITMQ_PORT=5672
      - MAIL_USERNAME_1=${MAIL_USERNAME_1}
      - MAIL_PASSWORD_1=${MAIL_PASSWORD_1}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - rabbit-net

networks:
  rabbit-net:
    driver: bridge
